"""Curated example problems for the StateScope demo.

Every example is a real DriftMath :class:`Problem` (so it carries a SymPy-verified gold
trace -- the ground truth the demo compares a model against). No dataset, no labels, no
training: these are generated by the families and the CAS oracle supplies the gold state.

Each entry is deliberately a *trap* -- a place multi-step solvers tend to lose the thread
(extraneous roots, dropped domains, off-by-one recurrences, stale bindings, reused lemmas).

Because every entry is generator-backed, it can also be **reinstantiated with fresh
parameters** on demand (:func:`fresh_variant`) -- the demo's live proof that evaluation
instances are dynamic, not a static test file. Variants are session-scoped and addressed
as ``<base_id>#<seed>``.
"""

from __future__ import annotations

import random
from collections import OrderedDict

from driftmath.families.family_a import FamilyA
from driftmath.families.family_b import FamilyB
from driftmath.families.family_c import FamilyC
from driftmath.families.family_d import FamilyD
from driftmath.io.schema import Problem

# Pre-generate family instances we will hand-pick from (deterministic seeds).
_A = FamilyA().generate(8, seed=3)
_B = FamilyB().generate(8, seed=0)
_C = FamilyC().generate(9, seed=5)
_D = FamilyD().generate(6, seed=1)

_FAMILY_GENS = {"a": FamilyA, "b": FamilyB, "c": FamilyC, "d": FamilyD}
_REGEN_BATCH = 12  # instances per regeneration attempt (raises the template hit rate)


def _first(problems: list[Problem], **meta) -> Problem:
    for p in problems:
        if all(p.meta.get(k) == v for k, v in meta.items()):
            return p
    raise KeyError(meta)


# "regen" records how to reinstantiate the same trap with fresh parameters:
# (family key, meta filter used to pick the template out of a generated batch).
_CURATED: list[dict] = [
    {
        "id": "radical_extraneous",
        "title": "Radical equation with an extraneous root",
        "difficulty": "trap",
        "blurb": "Squaring is irreversible: it manufactures a root that the domain x ≥ 0 must reject. Models routinely keep both.",
        "problem": _first(_B, template="radical"),
        "regen": ("b", {"template": "radical"}),
    },
    {
        "id": "log_domain",
        "title": "Logarithmic equation (mind the domain)",
        "difficulty": "hard",
        "blurb": "The log domain constraint has to be carried the whole way; drop it and the 'solution' is silently wrong.",
        "problem": _first(_B, template="log"),
        "regen": ("b", {"template": "log"}),
    },
    {
        "id": "abs_branches",
        "title": "Absolute-value equation: both branches",
        "difficulty": "medium",
        "blurb": "Two ± branches must both survive to the end. Forgetting one halves the solution set.",
        "problem": _first(_B, template="abs"),
        "regen": ("b", {"template": "abs"}),
    },
    {
        "id": "rational_exclusion",
        "title": "Rational equation: cancel with an exclusion",
        "difficulty": "hard",
        "blurb": "Cancelling a factor is only valid with x ≠ excluded recorded. The exclusion is exactly what gets forgotten.",
        "problem": _first(_B, template="rational"),
        "regen": ("b", {"template": "rational"}),
    },
    {
        "id": "two_state_recurrence",
        "title": "Coupled two-state recurrence",
        "difficulty": "very hard",
        "blurb": "x and y feed each other every step. A single swapped cross-binding propagates to the final answer.",
        "problem": _first(_C, kind="two_state"),
        "regen": ("c", {"kind": "two_state"}),
    },
    {
        "id": "linear_recurrence",
        "title": "Linear recurrence to aₙ",
        "difficulty": "hard",
        "blurb": "Iterating aₙ₊₁ = p·aₙ + q is an off-by-one minefield: report aₙ when the state is really aₙ₋₁.",
        "problem": _first(_C, kind="linear"),
        "regen": ("c", {"kind": "linear"}),
    },
    {
        "id": "compound_balance",
        "title": "Compound balance (exact rationals)",
        "difficulty": "hard",
        "blurb": "Grow by a percentage, then withdraw, every step. Stale accumulators creep in fast.",
        "problem": _first(_C, kind="finance"),
        "regen": ("c", {"kind": "finance"}),
    },
    {
        "id": "u_substitution",
        "title": "u-substitution integral",
        "difficulty": "hard",
        "blurb": "u must stay live across the whole integral and be discharged at the end — leaving the answer in u is the classic miss.",
        "problem": _first(_A, subtype="usub"),
        "regen": ("a", {"subtype": "usub"}),
    },
    {
        "id": "binding_chain",
        "title": "Chained variable bindings",
        "difficulty": "medium",
        "blurb": "A web of let-bindings with fan-in > 1. Reuse a stale value and the chain quietly diverges.",
        "problem": _first(_A, subtype="chain"),
        "regen": ("a", {"subtype": "chain"}),
    },
    {
        "id": "triple_product_derivative",
        "title": "Triple-product derivative (log · f · g)",
        "difficulty": "very hard",
        "blurb": "Product rule across three factors with a log domain; each term is a reusable lemma and the sum has fan-in 3.",
        "problem": _first(_D, kind="product3"),
        "regen": ("d", {"kind": "product3"}),
    },
    {
        "id": "chain_product_derivative",
        "title": "Chain-rule × product derivative",
        "difficulty": "very hard",
        "blurb": "A composite factor whose derivative is itself a lemma chain (du → df). Reused lemmas, deep dependency.",
        "problem": _first(_D, kind="chain_product"),
        "regen": ("d", {"kind": "chain_product"}),
    },
]

EXAMPLES: dict[str, dict] = {e["id"]: e for e in _CURATED}

# Session-scoped fresh reinstantiations, addressed as "<base_id>#<seed>".
_VARIANTS: OrderedDict[str, Problem] = OrderedDict()
_MAX_VARIANTS = 64


def _entry(e: dict, problem: Problem, *, id_: str, seed: int | None = None) -> dict:
    return {
        "id": id_,
        "title": e["title"],
        "difficulty": e["difficulty"],
        "blurb": e["blurb"],
        "family": problem.family,
        "problem_text": problem.problem_text,
        "n_steps": len(problem.gold_trace.steps),
        "seed": seed,
    }


def list_examples() -> list[dict]:
    """Lightweight list for the UI (no heavy trace payloads)."""
    return [_entry(e, e["problem"], id_=e["id"]) for e in _CURATED]


def fresh_variant(example_id: str, seed: int | None = None) -> dict:
    """Reinstantiate a curated trap with fresh parameters; register and describe it.

    Uses the same family generator and template filter that produced the curated
    instance, trying a few seeds until the template appears in the batch.
    """
    base_id = example_id.split("#")[0]
    e = EXAMPLES.get(base_id)
    if e is None:
        raise KeyError(f"unknown example {base_id!r}")
    fam_key, match = e["regen"]
    s0 = seed if seed is not None else random.randrange(1, 100_000)
    for s in range(s0, s0 + 8):
        try:
            problem = _first(_FAMILY_GENS[fam_key]().generate(_REGEN_BATCH, seed=s), **match)
        except KeyError:
            continue
        vid = f"{base_id}#{s}"
        _VARIANTS[vid] = problem
        while len(_VARIANTS) > _MAX_VARIANTS:
            _VARIANTS.popitem(last=False)
        return _entry(e, problem, id_=vid, seed=s)
    raise KeyError(f"could not regenerate {base_id!r} near seed {s0}")


def get_problem(example_id: str) -> Problem:
    if example_id in _VARIANTS:
        return _VARIANTS[example_id]
    return EXAMPLES[example_id]["problem"]
